### ISSUE TITLE
repe prefix prints out as rep in udcli

### ISSUE THREAD

**Issue by mgpleszkoch** [vmt/udis86#10]
00000000000019b0 f3a7             rep cmpsd
00000000000019b2 f366a7           rep cmpsw
00000000000019b5 f3a6             rep cmpsb

0000000000001a08 f3af             rep scasd
0000000000001a0a f366af           rep scasw
0000000000001a0d f3ae             rep scasb

These should all have "repe" instead of "rep".

**Comment by vmt** [comment]
Thank you reporting the issue, mgpleszkoch
