### ISSUE TITLE
loopnz should be loopne

### ISSUE THREAD

**Issue by ghghost** [vmt/udis86#20]
For consistency with repne.

**Comment by mgpleszkoch** [comment]
And also for consistency with loope.

**Comment by mgpleszkoch** [comment]
While we're at it, how about changing pusha to pushaw, and popa to popaw, so that they mirror the pushfw, pushfd, popfw, and popfd instructions.

**Comment by ghghost** [comment]
The Intel 16-bit mnemonics are simply pusha, popa, pushf, popf. I suggest changing pushfw and popfw to pushf and popf, since udis86 generally follows the Intel mnemonics.

**Comment by ghghost** [comment]
This is included in issue #17, and is fixed by the fix for that issue.
