### ISSUE TITLE
Missing instructions: pextrw (66 0f 3a 15), cmpxch16b, all the AES instructions

### ISSUE THREAD

**Issue by ghghost** [vmt/udis86#22]
These need to be added.

**Comment by ghghost** [comment]
cmpxch16b is an alternate mnemonic for cmpxchg8b that is used when REX.W = 1. There is currently no way to represent this in optable.xml, although a way to indicate REX.W = 0 or 1 is required will be needed when we add the AVX instructions.

**Comment by vmt** [comment]
/o=64 is a (hackish) way of specifying REX.W=1.
