### ISSUE TITLE
optable.xml: <class> and <vendor> can be children of either <instruction> or <def>

### ISSUE THREAD

**Issue by ghghost** [vmt/udis86#35]
Is this deliberate? If so, I would like to document it; if not, I would like to fix it. I don't have an opinion either way, but since I'm going to be adding instruction definitions, I want to do it consistently one way or the other.

**Comment by vmt** [comment]
This is deliberate. This allows you to either specify the class/vendor on an overall instruction basis, or on a per-definition basis.
