### ISSUE TITLE
API changed between 1.7 and 1.7.1

### ISSUE THREAD

**Issue by mrjbq7** [vmt/udis86#40]
The layout of `ud_operand` and `ud` have changed.

Are those part of the public API?  Seems like they shouldn't change in minor point releases?

Is there a way to get the version of `ud` so a client library could determine which layout to use when using it from another language via an FFI bridge approach?

**Comment by vmt** [comment]
The layout of either of those structures is not intended to be part of the public api, but I can see how it is useful for something like ffi. This did not occur to me, apologies for the breakage. 

I don't provide a way to inspect the version of the library, yet. I'll can a add new interface and make a quick 1.7.2 release for this. Let me know if you have any more suggestions to go along with it.

**Comment by mrjbq7** [comment]
You don't need to do a quick release just for a version API since we aren't a huge userbase of your library, but I'll think of any other feedback I might have.

If you're curious, here is a link to our tracking issue, https://github.com/slavapestov/factor/issues/894, since it relates to having the structures defined using our FFI, (https://github.com/slavapestov/factor/blob/master/basis/tools/disassembler/udis/udis.factor#L20), you can see its a little fragile when the underlying structures change.

Not a big deal, but we'll need to find a workaround even if it just means having the user specify which version they are using ahead of time.

**Comment by vmt** [comment]
Sounds good.

It wasn't immediately obvious to me from the factor project, but do you use the struct fields for anything other than operands and prefixes? Would it help if all of the api for accessing fields were to become function based, i.e. no more struct fields.

**Comment by mrjbq7** [comment]
No, we don't use the contents at all, in fact all we really care about is that we malloc a `ud` struct with the right length, which we can pass to `ud_init`.  The contents are opaque to us...

**Comment by mrjbq7** [comment]
Which leads me to an idea for a workaround, I could just malloc the larger of the old struct size and the new struct size.  That should probably work for both versions and is an easy fix.

**Comment by mrjbq7** [comment]
I found a workaround, so can close this bug.  If `ud` and `ud_operand` aren't public, they probably shouldn't be in public header files... and the version thing would be a nice-to-have, but since I have a workaround, no longer necessary.

Thanks for the great project!
