### ISSUE TITLE
REPE instructions incorrectly disassembled

### ISSUE THREAD

**Issue by radare** [vmt/udis86#45]
Originally reported here: https://github.com/radare/radare2/issues/97

According to the Intel® 64 and IA-32 Architectures Software Developer’s Manual,

"rep cmpsd" should be "repe cmpsd"
"rep scasd" should be "repe scasd"

example:

```
% rasm2 -d F3A7
rep cmpsd
% rasm2 -d F3AF
rep scasd
```

**Comment by vmt** [comment]
This was actually fixed in https://github.com/vmt/udis86/commit/306606f4898e7e793d00d393d39989f370a42849, available in release 1.7.1.

```
$ echo "f3 af" | udcli/udcli -x
0000000000000000 f3af             repe scasd

$ echo "f3 a7" | udcli/udcli -x
0000000000000000 f3a7             repe cmpsd
```
