### ISSUE TITLE
Is it possible to get instruction dependency graph?

### ISSUE THREAD

**Issue by p0nce** [vmt/udis86#63]
Just curious.

eg:

(a) mov ecx, 4
(b) mov ebx, 5
(c) shr ebx, cl    // depends on (a) and (b)

It would obviously make problems for conditional jumps.

**Comment by vmt** [comment]
Hi p0nce, the answer is no. libudis86 is really a dumb, straight forward library that decodes a stream of bytes and gives you the decoded bits.

You can, at least in theory, use the library to build a dependency graph based on the decode info.
