### ISSUE TITLE
udis86 does not recognize rdrand

### ISSUE THREAD

**Issue by jamieiles** [vmt/udis86#64]
rdrand isn't correctly decoded:

```
  echo 48 0f c7 f0 | ~/src/udis86/udcli/udcli -64 -x
  0000000000000000 480fc7f0         invalid
```

and this comes up in the kernel:

```
  # define RDRAND_LONG  ".byte 0x48,0x0f,0xc7,0xf0"
```

But I can't find a way to describe this in the xml that doesn't cause overwriting of existing opcodes, it looks like it clashes with the cmpxchg opcodes.

**Comment by vmt** [comment]
Fixed. Just needed to explicitly disambiguate /mod for the other instructions starting with 0f c7.

```
$ echo 48 0f c7 f0 | udcli/udcli -x -64
0000000000000000 480fc7f0         rdrand rax
```
