### ISSUE TITLE
Segment prefix not printed by udcli for cmpsd, cmpsw, cmpsb instructions

### ISSUE THREAD

**Issue by mgpleszkoch** [vmt/udis86#9]
The last three instructions are missing their "gs" segment prefix in the printout:

000000000000196c a7               cmpsd
000000000000196d 66a7             cmpsw
000000000000196f a6               cmpsb
0000000000001970 65a7             cmpsd
0000000000001972 6566a7           cmpsw
0000000000001975 65a6             cmpsb

By way of comparison, here are the corresponding versions of lodsd, lodsw, lodsb:

0000000000001977 ad               lodsd
0000000000001978 66ad             lodsw
000000000000197a ac               lodsb
000000000000197b 65ad             gs lodsd
000000000000197d 6566ad           gs lodsw
0000000000001980 65ac             gs lodsb

**Comment by mgpleszkoch** [comment]
This problem also occurs with the xlatb instruction.

**Comment by vmt** [comment]
Thanks for reporting the issue, fixed.
